version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: BookService
    ports:
      - "3307:3306"
    networks:
      - microservice-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - microservice-network

  discovery:
    image: discovery-service:0.0.1
    container_name: discovery
    ports:
      - "8761:8761"
    depends_on:
      - mysql
      - redis
    networks:
      - microservice-network

  bookservice:
    image: book-service:0.0.1
    container_name: bookservice
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_PORT: 3306
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    networks:
      - microservice-network

  api-gateway:
    image: api-gateway:0.0.1
    container_name: api-gateway
    ports:
      - "8085:8085"
    depends_on:
      - discovery
    networks:
      - microservice-network

  orderservice:
    image: order-service:0.0.1
    container_name: orderservice
    ports:
      - "8083:8083"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_PORT: 3306
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    networks:
      - microservice-network

  cartservice:
    image: cart-service:0.0.1
    container_name: cartservice
    ports:
      - "8084:8084"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_PORT: 3306
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    networks:
      - microservice-network

  userservice:
    image: user-service:0.0.1
    container_name: userservice
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_PORT: 3306
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    networks:
      - microservice-network

networks:
  microservice-network:
    name: microservice-network
    driver: bridge