version: '3'
services:
  discovery:
    image: discovery-service:0.0.1
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  api-gateway:
    image: api-gateway:0.0.1
    container_name: api-gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    ports:
      - "8085:8085"
    depends_on:
      - discovery
    networks:
      - microservice-network

networks:
  microservice-network:
    name: microservice-network
    driver: bridge
