version: "3.8"

services:
  mysql-book:
    image: mysql:latest
    container_name: mysql-book
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: BookService
    ports:
      - "3307:3306"
    networks:
      - microservice-network
  mysql-user:
    image: mysql:latest
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: UserSerVice
    ports:
      - "3308:3306"
    networks:
      - microservice-network
  mysql-order:
    image: mysql:latest
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: OrderService
    ports:
      - "3309:3306"
    networks:
      - microservice-network
  mysql-cart:
    image: mysql:latest
    container_name: mysql-cart
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: CartService
    ports:
      - "3300:3306"
    networks:
      - microservice-network
  mysql-jwt:
    image: mysql:latest
    container_name: mysql-jwt
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: JWTService
    ports:
      - "3301:3306"
    networks:
      - microservice-network
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - microservice-network

  discovery:
    image: discovery-service:0.0.1
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  jwt-service:
    image: jwt-service:0.0.1
    container_name: jwt-service
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-jwt
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_PORT: 3306
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql-jwt
      - redis
    networks:
      - microservice-network

  bookservice:
    image: book-service:0.0.1
    container_name: bookservice
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysql-book
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_PORT: 3306
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql-book
      - redis
    networks:
      - microservice-network

  api-gateway:
    image: api-gateway:0.0.1
    container_name: api-gateway
    ports:
      - "8085:8085"
    depends_on:
      - discovery
    networks:
      - microservice-network

  orderservice:
    image: order-service:0.0.1
    container_name: orderservice
    ports:
      - "8083:8083"
    environment:
      MYSQL_HOST: mysql-order
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_PORT: 3306
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql-order
      - redis
    networks:
      - microservice-network

  cartservice:
    image: cart-service:0.0.1
    container_name: cartservice
    ports:
      - "8084:8084"
    environment:
      MYSQL_HOST: mysql-cart
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_PORT: 3306
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql-cart
      - redis
    networks:
      - microservice-network

  userservice:
    image: user-service:0.0.1
    container_name: userservice
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: mysql-user
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_PORT: 3306
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql-user
      - redis
    networks:
      - microservice-network

networks:
  microservice-network:
    name: microservice-network
    driver: bridge
