spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: JWTService
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
        - id: BookService
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/**
          filters:
            - name: AuthenticationFilter
        - id: UserService
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/**
          filters:
            - name: AuthenticationFilter
        - id: OrderService
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/**
          filters:
            - name: AuthenticationFilter 
        - id: CartService
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/**
          filters:
            - name: AuthenticationFilter  