spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: BookService
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/**
        - id: UserService
          uri: http://localhost:8082
          predicates:
            - Path=/api/v2/**
#        - id: OrderService
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/v3/**
#        - id: CartService
#          uri: http://localhost:8084
#          predicates:
#            - Path=/api/v4/**
