
resilience4j.ratelimiter:
  instances:
    orderService:
      limitForPeriod: 2
      limitRefreshPeriod: 4s
      timeoutDuration: 10s
      registerHealthIndicator: true
      eventConsumerBufferSize: 100

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
